// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0D_is4VWVwd0XFW8Su8NbFB9xhq4azRw',
    appId: '1:540564705184:web:24bf21c08398c054189ec5',
    messagingSenderId: '540564705184',
    projectId: 'godownstorage-976fc',
    authDomain: 'godownstorage-976fc.firebaseapp.com',
    storageBucket: 'godownstorage-976fc.appspot.com',
    measurementId: 'G-ZH0Z1SCCFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRgVQQwH0_9glHP13MW-vrBa3_Qz45ZII',
    appId: '1:540564705184:android:d2527631a7e5c307189ec5',
    messagingSenderId: '540564705184',
    projectId: 'godownstorage-976fc',
    storageBucket: 'godownstorage-976fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMRzhlVCuY358ixgqkaBCeCgZfeb45luo',
    appId: '1:540564705184:ios:0cf75b7c2b453e10189ec5',
    messagingSenderId: '540564705184',
    projectId: 'godownstorage-976fc',
    storageBucket: 'godownstorage-976fc.appspot.com',
    iosBundleId: 'com.example.godownManagementFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMRzhlVCuY358ixgqkaBCeCgZfeb45luo',
    appId: '1:540564705184:ios:0cf75b7c2b453e10189ec5',
    messagingSenderId: '540564705184',
    projectId: 'godownstorage-976fc',
    storageBucket: 'godownstorage-976fc.appspot.com',
    iosBundleId: 'com.example.godownManagementFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0D_is4VWVwd0XFW8Su8NbFB9xhq4azRw',
    appId: '1:540564705184:web:e859ba67651810e5189ec5',
    messagingSenderId: '540564705184',
    projectId: 'godownstorage-976fc',
    authDomain: 'godownstorage-976fc.firebaseapp.com',
    storageBucket: 'godownstorage-976fc.appspot.com',
    measurementId: 'G-QDSK5V4HTZ',
  );
}
